version: '3.8'

services:
  # MongoDB
  mongodb:
    image: mongo:6.0
    container_name: zipurl-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongodb_data:/data/db

  # Redis
  redis:
    image: redis:7.2
    container_name: zipurl-redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data

  # API Spring Boot
  api:
    build: .
    container_name: zipurl-api
    ports:
      - "${SPRING_PORT}:8080"
    depends_on:
      - mongodb
      - redis
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017/${MONGO_DB}?authSource=admin
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: ${REDIS_PORT}
      SPRING_REDIS_PASSWORD: ${REDIS_PASSWORD}

volumes:
  mongodb_data:
  redis_data:
