spring.application.name=ZipURL
server.port=8080
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
spring.redis.host=${SPRING_REDIS_HOST}
spring.redis.port=${SPRING_REDIS_PORT}
spring.data.redis.type=redis
spring.data.redis.repository.enabled=false


