spring.data.mongodb.uri=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:${MONGO_PORT}/${MONGO_DB}?authSource=admin

spring.redis.host=localhost
spring.redis.port=${REDIS_PORT}
spring.redis.password=
spring.redis.database=0
spring.redis.timeout=60000